// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NODE_VERSION: "22.14.0";
	TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	EMAIL_QUEUE: Queue;
}
